# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

category1 = Category.create(name: "Economy car")
category2 = Category.create(name: "Family car")
category3 = Category.create(name: "Saloons")
category4 = Category.create(name: "Luxury vehicle")
category5 = Category.create(name: "Sports cars")
# category6 = Category.create(name: "Off-roaders")

category1.items.create(name: "Fiat Panda", price: 25.6 , description: "The second generation, codenamed Model 169, first appeared in 2003. In its development phase, the new Panda was originally intended to be called 'Gingo'. However, this name was considered to be too similar to the Renault Twingo, so Fiat decided to continue with the Panda name, although it has almost no direct engineering link to the original 1980 car.")
category1.items.create(name: "Honda Life", price: 27 , description: "The original Life range was offered as a two-door or four-door hatchback and in a three-door wagon model (also sold as a commercial van), replacing the Honda NIII360. Compared with the previous Honda minicar series, passenger comfort was improved to make this a better family car - indeed, Honda's target was to make a kei which was as habitable as a period 1-liter car.[1] The wheelbase, at 2,080 mm (82 in), was eight cm longer than that of the predecessor. The entire Life range had a water-cooled Honda EA 356 cc engine, usually producing 30 PS (30 hp) at 8,000 rpm.[2] which began as the air-cooled engine borrowed from the Honda CB450 motorcycle. Top speed of a sedan is 105 km/h.[3] The sprint to 100 km/h came up in 34.9 seconds in a period test.[4] In September 1972, the tall and curiously shaped 'Life Step Van' was introduced, with either three or five doors. A pickup version of this was later added to the lineup, but had minimal impact on the market.")
category2.items.create(name: "Peugeot 308", price: 29.7, description: "The Peugeot 308 is a small family car produced by the French car manufacturer Peugeot. It was unveiled on 5 June 2007, and launched in September 2007.[1] Its development code was 'Project T7',[2] and is the first car of the X08 generation of Peugeot models. The 308 features a range of petrol and diesel engine options. In March 2011, the 308 received a facelift and it premiered at the Geneva Motor Show. A second generation was unveiled in 2013 and it was awarded as the 2014 European Car of the Year.")
category2.items.create(name: "Toyota Auris", price: 28.5, description: "The Toyota Auris is a compact hatchback derived from the Toyota Corolla, manufactured and sold by Toyota. Introduced in 2006, the first generation shared the E150 platform with the Corolla, while the second generation compact five-door hatchback and station wagon called the Touring Sports uses the E180 platform. The name 'Auris' is based on the Latin word for 'gold', 'aurum'.
In Europe, Toyota positioned the Auris as the replacement for the Corolla hatchback, while the notchback sedan continued with the Corolla nameplate.")
category2.items.create(name: "Renault Megane", price: 28, description: "The Renault Mégane is a small family car produced by the French manufacturer Renault since 1995, and was the successor to the Renault 19.
The Mégane has been offered in three- and five-door hatchback, saloon, coupé, convertible and estate bodystyles at various points in its lifetime, and has been through three generations. The first generation was largely based on its predecessor, the 19, and utilized modified versions of that car's drivetrain and chassis. In 1996, the Mégane Scénic compact MPV was introduced, using the same mechanical components as the hatchback Mégane.")
category3.items.create(name: "Ford Falcon", price: 29.3, description: "The Ford Falcon was a full-sized car manufactured by the Ford Motor Company of Australia from 1960 to 2016. From the XA series of 1972 onward, each Falcon and range of derivates have been designed, developed, and built in Australia, following the phasing out of the American-influenced Falcon of 1960 to 1971, which had been re-engineered locally as the XK to XY series for the harsher Australian conditions. The luxury-oriented Ford Fairmont model joined the range from 1965. Luxury long-wheelbase derivative versions called the Ford Fairlane and LTD arrived in 1967 and 1973, respectively (with production ending in 2007).")
category3.items.create(name: "Kia Optima", price: 33.6, description: "The Kia Optima is a mid-sized 4-door sedan manufactured by Kia Motors since 2000 and marketed globally through various nameplates. First generation cars were mostly marketed as the Optima, although the Kia Magentis name was used in Europe and Canada when sales began there in 2002. For the second generation models, Kia used the Kia Lotze & Kia K5 name for the South Korean market, and the Magentis name globally, except in the United States and Malaysia where the Optima name was retained. The Optima name is now going to be used for all markets except China, where they will also use the South Korean market name.")
category3.items.create(name: "Dodge Charger", price: 35.8, description: "The Dodge Charger LX is a rear-wheel drive four-door automobile introduced in February 2005. Built by Dodge, the car was created to continue the Dodge Charger line, and replaced the Dodge Intrepid as Dodge's full-size sedan.[2] The Charger shares the LX platform with the Chrysler 300, the newer fourth generation Dodge Challenger, and the discontinued Dodge Magnum.")
category4.items.create(name: "Audi A4", price: 42.3, description: "The Audi A4 is a line of compact executive cars produced since late 1994 by the German car manufacturer Audi, a subsidiary of the Volkswagen Group.
The A4 has been built in five generations and is based on the Volkswagen Group B platform. The first generation A4 succeeded the Audi 80. The automaker's internal numbering treats the A4 as a continuation of the Audi 80 lineage, with the initial A4 designated as the B5-series, followed by the B6, B7, B8 and the B9. The B8 and B9 versions of the A4 are built on the Volkswagen Group MLB platform shared with many other Audi models and potentially one Porsche model within Volkswagen Group.
The Audi A4 automobile layout consists of a longitudinal engine front-engine design, with transaxle-type transmissions mounted at the rear of the engine. The cars are front-wheel drive, or on some models, 'quattro' all-wheel drive.
The A4 is available as a sedan and station wagon. The second (B6) and third generations (B7) of the A4 also had a convertible version, but the B8 version of the convertible became a variant of the Audi A5 instead as Audi got back into the compact executive coupé segment.")
category4.items.create(name: "Jaguar XF", price: 45.5, description: "The Jaguar XF is an executive/mid-size luxury car and estate produced by British car manufacturer Jaguar. It was first unveiled in autumn 2007 as a replacement for the Jaguar S-Type.")
category4.items.create(name: "Lexus LS", price: 41.3, description: "The Lexus LS (Japanese: レクサス・LS, Rekusasu LS) is a full-size luxury car (F-segment in Europe) serving as the flagship model of Lexus, the luxury division of Toyota. For the first four generations, all LS models featured V8 engines and were predominantly rear-wheel-drive, with Lexus also offering all-wheel-drive, hybrid, and long-wheelbase variants. The fifth generation changed to using a V6 engine with no V8 option.")
category5.items.create(name: "Volkswagen Golf GTi", price: 47.3, description: "The Volkswagen Golf is a small family car produced by the German manufacturer Volkswagen since 1974, marketed worldwide across seven generations, in various body configurations and under various nameplates – such as the Volkswagen Rabbit in the United States and Canada (Mk1 and Mk5), and as the Volkswagen Caribe in Mexico (Mk1).
The original Golf Mk1 was a front-wheel drive, front-engined replacement for the air-cooled, rear-engined, rear-wheel drive Volkswagen Beetle.")
category5.items.create(name: "BMW M5", price: 55.2, description: "The BMW M5 is a Sport sedan version of the 5 Series executive car built by the Motorsport division of BMW. Beginning production in 1986, the first incarnation of the M5 was hand-built utilizing the 535i chassis and a modified BMW M1 engine, making it the fastest production sedan at the time of its introduction. Versions of the M5 have been built from subsequent generations of the 5-Series platform.")
category5.items.create(name: "Dodge SRT-4", price: 50, description: "The Dodge Neon SRT-4 is a sport compact car manufactured by Dodge from 2003 to 2005. A turbocharged variant of the Neon,[1] the car was developed by DaimlerChrysler's in house PVO (Performance Vehicle Operations) tuner group. PVO was officially renamed SRT (Street and Racing Technology) in 2004. The '4' in the SRT-4's name denotes the number of cylinders of the engine.[2] ACR (American Club Racing) and Commemorative Edition models were later introduced as well.")
# item15 = category5.items.create(name: "Lotus Cortina", price: 77.8, description: "")
# item15 = category5.items.create(name: "Mitsubishi EVO", price: 52.6, description: "")
# item15 = category5.items.create(name: "Aston Martin V8", price: 98.4, description: "")
#
# item16 = category6.items.create(name: "Land Rover Freelander", price: 85.6 , description: "")
# item17 = category6.items.create(name: "Mitsubishi Pajero", price: 85.3, description: "")
# item18 = category6.items.create(name: "Mahindra Scorpio", price: 80.2, description: "")
# item18 = category6.items.create(name: "Jeep Patriot", price: 76.6, description: "")
# item18 = category6.items.create(name: "Land Rover Discovery", price: 96.4, description: "")
# item18 = category6.items.create(name: "Toyota FJ Cruiser", price: 94.3, description: "")